Repository w3c/webauthn, pull requests merged in 2018-03, with the labels that each got.

#835 Remove vestigial reference to CollectedClientData/clientExtensions
  index.bs
Labels: type:technical

#840 fix linking errors, ref PublicKeyCredentialCreationOptions rather than…
  index.bs
Labels: type:editorial

#825 Add non-ASCII RP display name example
  index.bs
Labels: type:editorial

#826 Explicitly recommend generating AAGUIDs randomly.
  index.bs
Labels: subtype:algorithms/WebIDL, type:technical

#830 Add User Public Key as alias of Credential Public Key
  index.bs
Labels: type:editorial

#843 add link to WD-webauthn-20180315 (WD-09)
  index.bs
Labels: type:editorial
