Repository w3c/webauthn, pull requests merged in 2018-05, with the labels that each got.

#883 Clean up cross-spec refs in PR #861
  index.bs
Labels: type:editorial

#881 Clarify that authentication use case example requires pairing the phone first
  index.bs
Labels: type:editorial

#861 Clarify U2F attestation verification instructions
  index.bs
Labels: subtype:attestation, type:editorial

#892 Use |authData| in both RP operations
  index.bs
Labels: subtype:rp-ops, type:editorial

#880 Change "with string-valued keys" to "whose keys are strings"
  index.bs
Labels: priority:low, type:editorial

#836 Clarify the U2F Attestation format to have a single certificate
  index.bs
Labels: subtype:attestation, type:technical

#887 Fixed incorrect field size that makes all letters to overlap each other
  images/fido-signature-formats-figure2.svg
Labels: type:editorial

#896 Track initial COSE algorithm registrations made for WebAuthn
  index.bs
Labels: stat:breaking, type:technical

#829 Add RP conformance section on ignoring attestation
  index.bs
Labels: subtype:impl-cons, type:editorial

#897 Replace [[FIDOReg]] with [[FIDO-Registry]]
  index.bs
Labels: priority:low, type:editorial

#903 Add an “internal” AuthenticatorTransport.
  index.bs
Labels: type:editorial, type:technical

#924 Modify Location Extension description
  index.bs
Labels: type:editorial

#922 Fix formatting of Boolean values and type name
  index.bs
Labels: type:editorial

#913 Update FIDO references to newer documents
  index.bs
Labels: type:editorial

#918 Create draft-jones-webauthn-secp256k1 to register secp256k1 curve and algorithm identifiers
  draft-jones-webauthn-secp256k1.html
  draft-jones-webauthn-secp256k1.txt
  draft-jones-webauthn-secp256k1.xml
Labels: type:technical
