Repository w3c/webauthn, pull requests merged in 2018-07, with the labels that each got.

#974 fix #180: do not totally lose the term "WebAuthn Relying Party"
  index.bs
Labels: type:editorial

#977 fix #866: clarify sentence wrt challenges
  index.bs
Labels: type:editorial

#976 fix #493: be explicit about "same user" is verified at get() time as was verified at create() time
  index.bs
Labels: type:editorial

#986 fix 864: Note regarding CTAP2 integer keys vs webauthn string keys
  index.bs
Labels: type:editorial

#989 Add recommendation of scoping platform credentials to OS accounts
  index.bs
Labels: subtype:privacy-cons

#971 fix 364 timeout reasonable range
  index.bs
Labels: type:technical

#995 Disambiguate appid extension output behaviour
  index.bs
Labels: subtype:extensions, subtype:underspecifiedBehaviors, type:technical

#979 Authenticator taxonomy: Authenticator types
  index.bs
Labels: type:editorial

#993 Replace resident key terminology as proposed in #905
  index.bs
Labels: subtype:renaming, type:editorial

#951 Fix #593: employ PRECIS RFC8264 et al for 'name'-ish domstring values
  index.bs
Labels: i18n-tracking, stat:breaking, subtype:impl-cons, subtype:underspecifiedBehaviors, type:technical

#906 Add two abort paths for getting an assertion
  index.bs
Labels: type:technical

#994 Add table numbers and captions
  index.bs
Labels: type:editorial

#999 fix 933: authnr does not enforce RP ID being eTLD+1 of RP's origin
  index.bs
Labels: type:editorial

#997 Replace local/remote storage terms with client/server side
  index.bs
Labels: type:editorial

#1002 Make transaction authorization extensions authentication exts only
  index.bs
Labels: subtype:extensions, type:technical

#998 Precisize "platform" and "device" terminology
  index.bs
Labels: type:editorial

#1009 Clarify behaviour for authnrs not implementing signature counter
  index.bs
Labels: subtype:algorithms/WebIDL, type:editorial

#1005 fix 985 add abort path to createCredential alg
  index.bs
Labels: subtype:algorithms/WebIDL, type:technical

#1006 fix #939 add intro abort language to #getAssertion
  index.bs
Labels: subtype:algorithms/WebIDL, type:editorial

#1007 fix #24: add reg & authn flow diagrams
  images/webauthn-authentication-flow-01.svg
  images/webauthn-registration-flow-01.svg
  index.bs
Labels: type:editorial

#1013 update acks
  index.bs
Labels: type:editorial
