Repository w3c/webauthn, pull requests merged in 2018-09, with the labels that each got.

#1055 Adopt consistent case for section headings
  index.bs
Labels: type:editorial

#1036 Add Username Enumeration section to privacy considerations
  index.bs
Labels: subtype:privacy-cons, type:editorial

#1057 Add Credential Loss and Key Mobility section to security considerations
  index.bs
Labels: type:editorial

#375 add 'spec roadmap' section
  index.bs
Labels: type:editorial

#1066 enumerate actual supported attstn types for packed attestation statement format
  index.bs
Labels: type:editorial

#1062 Fix #1059: Update figure 1 to agree with figure 2 on clientDataJSON naming
  images/webauthn-registration-flow-01.svg
Labels: type:editorial

#1070 Spell out that values expressing attestation type are implementation specific
  index.bs
Labels: type:editorial

#1071 Make implementation-specificness of attestn.verif. return values more explicit
  index.bs
Labels: type:editorial

#1054 Highlight Basic/AttCA ambiguity in definitions and verification procedures
  index.bs
Labels: subtype:rp-ops, type:editorial, type:technical

#1069 Fix #1068: Fix a reference to privacy considerations
  index.bs
Labels: type:editorial

#1073 Issue #1045 - Add Platform-Specific Implementation Guidance
  index.bs
Labels: type:editorial

#1074 Issue #294 - Add a non-normative comment about snapshotting BufferSources
  index.bs
Labels: type:technical

#1081 Fix typo
  index.bs
Labels: type:editorial

#1077 note that obtaining a token binding ID is a client platform-specific operation
  index.bs
Labels: subtype:impl-cons, type:editorial

#1079 Un-revert change from 8e5f2e0 reverted in daf9522
  index.bs
Labels: type:editorial

#1083 Fix #1076 - Don't confuse extension optionality in Sec 10
  index.bs
Labels: type:editorial
