Repository w3c/webauthn, pull requests merged in 2018-04, with the labels that each got.

#856 fix 855: add link to CR
  index.bs
Labels: type:editorial

#827 Emphasise that the CollectedClientData can be extended.
  index.bs
Labels: subtype:impl-cons, type:editorial

#832 Address review comments by @kieun
  index.bs
Labels: type:editorial

#821 UVI modification with CDDL
  index.bs
Labels: type:technical
