Repository w3c/webauthn, pull requests merged in 2018-02, with the labels that each got.

#670 Fix #668: Recommend RPs to verify UP and UV flags
  index.bs
Labels: priority:low, type:editorial

#793 fix #792: use utf 8 decode directly
  index.bs
Labels: type:technical

#789 Add instructions for passing unknown extensions to authenticators
  index.bs
Labels: subtype:extensions, type:technical

#795 fix #794: RP registration operation inter-step refs
  index.bs
Labels: type:editorial

#802 Switch |tokenBindingId| to a structure.
  index.bs
Labels: type:technical

#805 Signature field clarification in attestation statement
  index.bs
Labels: type:technical

#808 Fix feature detection.
  index.bs
Labels: type:technical

#812 Make IANA COSE Algorithms values TBD with requested assignments
  index.bs
Labels: type:process

#811 Remove clientExtensions and authenticatorExtensions from CollectedClientData
  index.bs
Labels: stat:breaking, subtype:extensions, type:technical

#809 Plumb CTAP's authorized "already registered" error through to RP
  index.bs
Labels: type:technical

#810 Change from getClientExtensionResults function to clientExtensionResults attribute
  index.bs
Labels: stat:breaking, subtype:extensions, type:technical

#814 Change uses of acme.com to example.com
  index.bs
Labels: type:editorial

#815 Spelling and grammar corrections
  index.bs
Labels: type:editorial

#816 Revert clientExtensionResults attribute back to getClientExtensionResults function
  index.bs
Labels: stat:breaking, type:technical

#824 Updates for draft-hodges-webauthn-registries-01
  draft-hodges-webauthn-registries.html
  draft-hodges-webauthn-registries.txt
  draft-hodges-webauthn-registries.xml
Labels: type:process, type:technical
