Repository w3c/webauthn, pull requests merged in 2018-06, with the labels that each got.

#908 Remove (probably) outdated inline issue 2
  index.bs
Labels: subtype:privacy-cons, type:editorial

#901 Adopt definition list markdown notation for dfn blocks
  index.bs
Labels: type:editorial

#910 Trim unnecessary step from appId extension
  index.bs
Labels: type:technical

#888 Fixed example with incorrect allowCredential. Improved existing examples
  index.bs
Labels: type:editorial

#900 Finish up hot-plugging algorithm language
  index.bs
Labels: subtype:algorithms/WebIDL, subtype:underspecifiedBehaviors, type:editorial, type:technical

#940 PR #900 post-merge review changes
  index.bs
Labels: type:editorial

#945 Review of PR #944
  index.bs
Labels: type:editorial

#947 Update web-platform-tests URLs
  README.md
  index.bs
Labels: type:editorial, type:process

#942 Add Dockerfile with Bikeshed installed
  README.md
  docker/bikeshed/Dockerfile
  docker/bikeshed/README.md
Labels: type:process

#946 Add experimental Travis build with no Bikeshed cache
  .travis.yml
Labels: type:process

#949 Replace <pre class="idl">s with <xmp>s
  index.bs
Labels: type:editorial

#934 fix issue #932 clarify rpIdHash generation, minor editorial linking
  index.bs
Labels: type:editorial

#937 Note that the icon URL may be a data: URL
  index.bs
Labels: type:technical

#884 Add example of new device enrollment via roaming authenticator
  index.bs
Labels: subtype:impl-cons, type:editorial

#958 Address review comment
  index.bs
Labels: type:editorial

#957 Introduce WebAuthn Client Device term
  index.bs
Labels: type:editorial

#959 Mention rate limiting in UV definition
  index.bs
Labels: type:editorial

#941 Specify extension types in listing instead of prose
  index.bs
Labels: priority:low, type:editorial

#899 Document prevention of attacks on privacy
  index.bs
Labels: subtype:privacy-cons, type:editorial

#952 Improve clarity of |x5c| in packed and tpm attstmt verification procedures
  index.bs
Labels: type:editorial

#970 revise RP ID definition and Note
  index.bs
Labels: type:editorial

#967 ignored extn does not return a value
  index.bs
Labels: type:editorial, type:technical

#960 Tone back trust assumption in authn ceremony structures section
  index.bs
Labels: type:editorial
