Repository w3c/webauthn, pull requests merged in 2018-08, with the labels that each got.

#1017 fix #712 JSON-serialized client data is wrong
  index.bs
Labels: subtype:algorithms/WebIDL, type:technical

#1016 fix #1015 FAR should be FRR
  index.bs
Labels: type:editorial

#1026 Add bikeshed update to bikeshed Dockerfile
  docker/bikeshed/Dockerfile
Labels: type:process

#1021 Clarify that SafetyNet response uses base64url
  index.bs
Labels: type:editorial

#1024 Use final name for "serialize JSON to bytes"
  index.bs
Labels: type:editorial

#1038 [Spelling] Added missing "be"
  index.bs
Labels: type:editorial

#1023 fix #1012 determine Attested Credential Data length
  index.bs
Labels: type:editorial

#1030 Fix some minor editorial issues
  index.bs
Labels: type:editorial

#1032 Add note about actual implementations of appid.
  index.bs
Labels: type:editorial

#1047 change JeffH's affilitation
  index.bs
Labels: type:editorial

#1031 Define "bound" for credentials and use the term "scoped" where appropriate
  index.bs
Labels: type:editorial

#1041 Add privacy considerations about UV, PII and User Handle
  index.bs
Labels: subtype:privacy-cons, type:editorial
