Repository w3c/webauthn, pull requests merged in 2019-04, with the labels that each got.

#1186 Revert change to new TR link
  index.bs
Labels: process:meta-pr, type:editorial

#1182 Allow authenticators to do None instead of Self attestation
  index.bs
Labels: subtype:attestation, type:editorial, type:technical

#1161 Fixed various links, including new TR link
  index.bs
Labels: type:editorial

#1184 Update isUVPAA() scenario to agree with spec
  index.bs
Labels: type:editorial

#1192 Linked attestation statement format term in Section 8.1 to its defini…
  index.bs
Labels: type:editorial

#1193 Created linkable definition for WebAuthn Extensions and linked to it …
  index.bs
Labels: type:editorial
