Repository w3c/webauthn, pull requests merged in 2019-03, with the labels that each got.

#1140 Let requireUserPresence always be true in authenticator operations
  index.bs
Labels: subtype:CTAP, subtype:algorithms/WebIDL, type:technical

#1143 Determine appid extension output after authenticator returns
  index.bs
Labels: subtype:extensions, type:technical

#1118 Note that appid should be set to the previously used AppID
  index.bs
Labels: type:editorial

#1165 Add example of different RP ID and AppID
  index.bs
Labels: process:meta-pr, type:editorial

#1172 Move Angelo Liao to the Former Editors list
  index.bs
Labels: type:editorial

#1177 update registries draft per issue #1176
  draft-hodges-webauthn-registries.html
  draft-hodges-webauthn-registries.txt
  draft-hodges-webauthn-registries.xml
Labels: spec:webauthn-registries, type:editorial, type:process

#1168 Clarify relationship to trust path in RP registration step 16
  index.bs
Labels: type:editorial

#1159 Fix incorrect AuthenticatorAttachment description
  index.bs
Labels: type:editorial

#1190 Fix typo in Authentication example
  index.bs
Labels: type:editorial
