Repository w3c/webauthn, pull requests merged in 2019-12, with the labels that each got.

#1342 'loc' extension: cite permissions and geolocation specs
  index.bs
Labels: type:editorial

#1344 Use the new name for Coordinates
  index.bs
Labels: subtype:algorithms/WebIDL, type:editorial, type:technical

#1345 Reformat and rename AuthenticatorBiometricPerfBounds
  index.bs
Labels: subtype:algorithms/WebIDL, type:technical
