Repository w3c/webauthn, pull requests merged in 2019-05, with the labels that each got.

#1203 Add some embellishments to @equalsJeffH's suggestions
  index.bs
Labels: process:meta-pr, type:editorial

#1095 Rewrite security consideration on attestation and MitM attacks
  index.bs
Labels: subtype:security-cons, type:editorial

#1191 Initial proposal for modifications to resident key credential requirements
  index.bs
Labels: type:technical

#1195 Update Authenticator Definition
  index.bs
Labels: type:editorial

#1209 Rearrange terminology to be ordered by the first of the term aliases
  index.bs
Labels: priority:low, type:editorial

#1213 Fix typo in PR #1195
  index.bs
Labels: priority:low, type:editorial

#1217 Polish client device definition as suggested by @equalsJeffH
  index.bs
Labels: type:editorial

#1210 fix #1166: clarify extension input/output data type names
  index.bs
Labels: type:editorial

#1214 feature policy integration
  index.bs
Labels: type:technical

#1187 Revert "Revert change to new TR link"
  index.bs
Labels: type:editorial
