Repository w3c/webauthn, pull requests merged in 2019-10, with the labels that each got.

#1256 Add a WebDriver Virtual Authenticator extension
  index.bs
Labels: type:technical

#1310 ack Nina (automation/webdriver)
  index.bs
Labels: type:editorial

#1250 Add privacy considerations about credential IDs
  index.bs
Labels: subtype:privacy-cons, type:editorial

#1299 Recommend RPs to store transport hints
  index.bs
Labels: subtype:rp-ops, type:editorial

#1312 Clarify that RP is split into server and script
  index.bs
Labels: type:editorial

#1307 Add note about use of floating point in extensions passed through that clients do not recognize
  index.bs
Labels: type:editorial

#1322 revise draft-hodges-webauthn-registries per AD review and initiate work on rev -03
  draft-hodges-webauthn-registries.html
  draft-hodges-webauthn-registries.txt
  draft-hodges-webauthn-registries.xml
Labels: spec:webauthn-registries

#1317 Timeout considerations
  index.bs
Labels: type:WebPlatformTestNeeded, type:technical

#1329 Align with RFC8288, update .txt & .html to be actual rendered versions of .xml
  draft-hodges-webauthn-registries.html
  draft-hodges-webauthn-registries.txt
  draft-hodges-webauthn-registries.xml
  index.bs
Labels: spec:webauthn-registries

#1328 feature policy integration: add link to "allowed to use"
  index.bs
Labels: type:editorial

#1320 Update CDDL reference
  index.bs
Labels: type:editorial

#1321 Enhance spec roadmap section
  index.bs
Labels: type:editorial

#1313 Clarify assumptions about single-user authenticator and relation to UV
  index.bs
Labels: type:editorial

#1325 Add batch attestation as alias of basic attestation
  index.bs
Labels: type:editorial

#1326 Add explanatory note to step 3 in authenticatorMakeCredential
  index.bs
Labels: type:editorial

#1327 Explicitly mention running over TLS in WebAuthn API intro
  index.bs
Labels: type:editorial

#1319 Update timeout examples to better agree with guidelines
  index.bs
Labels: process:meta-pr, type:editorial

#1323 Create a way to reference the following figure
  index.bs
Labels: stat:Blocked, subtype:editorialConventions, type:editorial

#1324 Use CSS numbering for table references too
  index.bs
Labels: process:meta-pr, type:editorial

#1338 Re-merge PR #1324
  index.bs
Labels: type:process

#1332 Update note in RP definition to indicate that non-WebAuthn FIDO clien…
  index.bs
Labels: stat:puntable, type:editorial

#1335 name the protocol
  index.bs
Labels: type:editorial

#1337 Fix #1285 - Remove icons from PublicKeyCredentialEntity
  index.bs
Labels: subtype:privacy-cons, type:technical
