Repository w3c/webauthn, pull requests merged in 2019-09, with the labels that each got.

#1270 Improve authenticator taxonomy section
  index.bs
Labels: type:editorial

#1284 rename feature-identifier token: webauthn -> publickey-credentials (fix #1277)
  index.bs
Labels: type:editorial

#1288 Add RP ops step of storing new credential counter
  index.bs
Labels: subtype:rp-ops, subtype:underspecifiedBehaviors, type:technical

#1295 (Deja vu) webauthn => publickey-credentials
  index.bs
Labels: type:editorial

#1289 Initial proposal to fix #1287
  index.bs
Labels: type:technical

#1298 Divide security/privacy considerations into subsections by audience
  index.bs
Labels: subtype:privacy-cons, subtype:security-cons, type:editorial

#1301 fix publickey-credentials feature identifier tag
  index.bs
Labels: type:editorial
