Repository w3c/webauthn, pull requests merged in 2019-02, with the labels that each got.

#1154 update JeffH's affiliation
  index.bs
Labels: type:editorial, type:process

#1156 update spec to Level 2
  index.bs
Labels: priority:high, type:editorial, type:process

#1141 Recommend minimal basic attestation batches
  index.bs
Labels: subtype:impl-cons, subtype:privacy-cons, type:editorial

#1050 Provide transport information during registration.
  index.bs
Labels: stat:breaking, subtype:privacy-cons, type:editorial

#1145 Add None attestation case to RP ops registration step 16
  index.bs
Labels: subtype:attestation, subtype:rp-ops, type:technical

#1130 Add "Webauthn Authenticator" definition alias
  index.bs
Labels: type:editorial

#1142 Fix android-safetynet trust path
  index.bs
Labels: type:editorial

#1131 Add examples of authenticator types to Authenticator definition
  index.bs
Labels: type:editorial
