Repository w3c/webauthn, pull requests merged in 2019-06, with the labels that each got.

#1226 Polish definitions of credential key pair, private/public key
  index.bs
Labels: type:editorial

#1225 Clean up Bikeshed warnings
  index.bs
Labels: type:editorial

#1234 Re-merge PR #1165
  index.bs
Labels: type:process

#1222 Clean up RP operations
  index.bs
Labels: subtype:rp-ops, type:editorial

#1223 Add RP ops step of verifying credential key algorithm
  index.bs
Labels: subtype:rp-ops, type:technical

#1237 Use "authorization gesture" term in authenticator operations
  index.bs
Labels: type:editorial

#1230 Add guidance on using U2F key handles with appid extension
  index.bs
Labels: subtype:extensions, type:editorial

#1240 bikeshed cleanup: remove all trailing whitespace
  index.bs
Labels: type:editorial

#1238 Clarify that a single user might be several persons
  index.bs
Labels: stat:Discuss, type:editorial

#1239 Correctly refer to the FIDO U2F JavaScript API and informatively refe…
  index.bs
Labels: type:editorial

#1242 move the scenarios section up with the use cases section
  index.bs
Labels: type:editorial

#1243 coalesce HTML refs
  index.bs
Labels: type:editorial

#1241 bikeshed cleanup: refs
  index.bs
Labels: type:editorial
