Repository w3c/webauthn, pull requests merged in 2020-11, with the labels that each got.

#1507 Fix a link to userVerification parameter
  index.bs
Labels: type:editorial

#1508 Display OIDs consistently
  index.bs
Labels: subtype:editorialConventions, type:editorial

#1511 IANA registration for 'none' attestation statement format identifier
  index.bs
Labels: type:editorial

#1512 update IANA considerations per IANA instructions
  index.bs
Labels: type:editorial

#1513 Address review comment by @bdewater
  index.bs
Labels: type:editorial

#1509 ensure basic attestation type allows for self-signed attestation certs
  index.bs
Labels: type:technical

#1516 Update bikeshed files for Process 2020
  .bikeshed-include/header.include
  .bikeshed-include/status-CR.include
  .bikeshed-include/status-ED.include
  .bikeshed-include/status-WD.include
Labels: type:editorial, type:process

#1524 Fix out-of-sync step number
  index.bs
Labels: type:editorial
