Repository w3c/webauthn, pull requests merged in 2020-04, with the labels that each got.

#1390 Update signature counters section.
  index.bs
Labels: type:editorial

#1394 Prohibit Create Credential from cross-origin iframes
  index.bs
Labels: type:technical

#1405 Fix markup error in three headings.
  index.bs
Labels: type:editorial

#1399 remove unimplemented extensions (was: Update index.bs)
  index.bs
Labels: type:technical

#1408 Fix IANA Registration
  index.bs
Labels: type:technical

#1398 use '(client-side) discoverable credential' terminology
  index.bs
Labels: type:editorial

#1366 Add “enterprise” attestation type.
  index.bs
Labels: subtype:attestation, type:technical

#1375 Add more requirements for ClientDataJSON serialisation.
  index.bs
Labels: subtype:RP-impl-cons, subtype:algorithms/WebIDL, type:technical
