Repository w3c/webauthn, pull requests merged in 2020-09, with the labels that each got.

#1472 Virtual authenticators extension support
  index.bs
Labels: subtype:FeatureProposal, type:technical

#1480 Add security consideration on detecting non-WebAuthn accounts
  index.bs
Labels: subtype:RP-impl-cons, type:editorial

#1476 Update "feature policy" refs to new name "permissions policy" (#1473)
  index.bs
Labels: type:editorial

#1481 Remove the Psuedo-Random Function extension
  index.bs
Labels: type:editorial

#1483 Add note about fixed/empty user handles
  index.bs
Labels: type:editorial

#1470 Make largeBlobs explicit during create.
  index.bs
Labels: type:editorial, type:technical
