Repository w3c/webauthn, pull requests merged in 2020-02, with the labels that each got.

#1333 Add to sec cons a brief discussion of the sec properties accrued by authnr & client platform proximity
  index.bs
Labels: type:editorial

#1354 Remove the requirement accept and store a 64-byte minimum length for a name member’s value
  index.bs
Labels: type:technical

#1378 draft-hodges-webauthn-registries-04
  draft-hodges-webauthn-registries.html
  draft-hodges-webauthn-registries.txt
  draft-hodges-webauthn-registries.xml
Labels: spec:webauthn-registries
