Repository w3c/webauthn, pull requests merged in 2020-10, with the labels that each got.

#1488 Clarify signature format for packed attestations et al
  index.bs
Labels: type:technical

#1502 RP guidance on error conditions
  index.bs
Labels: type:editorial

#1500 Change variable name: uvpaaAvailable → uvpaAvailable
  index.bs
Labels: type:editorial

#1491 Adding Apple Anonymous Attestation Statement Format
  index.bs
Labels: subtype:attestation, type:technical

#1474 Abstracting the concept of Privacy CA/Attestation CA into Anonymization CA
  index.bs
Labels: subtype:attestation, type:editorial

#1497 Mention Intersection Observer v2 in sec considerations
  index.bs
Labels: security-tracker, type:editorial

#1506 Add Virtual Authenticator support for CTAP 2.1
  index.bs
Labels: type:technical
