Repository w3c/webauthn, pull requests merged in 2020-07, with the labels that each got.

#1424 PRF extension.
  index.bs
Labels: subtype:extensions, type:technical

#1440 Replace AuthenticationExtensionsAuthenticatorInputs with CDDL
  index.bs
Labels: subtype:editorialConventions, type:editorial, type:technical

#1450 Prohibit compressed points in COSE keys.
  index.bs
Labels: type:technical

#1451 Use conforming appidExclude client extension output
  index.bs
Labels: subtype:extensions, type:technical

#1452 Update RP ID definition to allow URL syntax or arbitrary strings
  index.bs
Labels: type:technical

#1455 Fix ambiguous {{appidExclude}} link
  index.bs
Labels: type:editorial

#1460 Do not wrap `otherUI` into credential ID
  index.bs
Labels: type:technical
