Repository w3c/webauthn, pull requests merged in 2020-03, with the labels that each got.

#1380 Proposed changes for draft-hodges-webauthn-registries-05
  draft-hodges-webauthn-registries.html
  draft-hodges-webauthn-registries.txt
  draft-hodges-webauthn-registries.xml
Labels: spec:webauthn-registries, type:editorial

#1384 re-gen .html & .txt files from .xml file
  draft-hodges-webauthn-registries.html
  draft-hodges-webauthn-registries.txt
  draft-hodges-webauthn-registries.xml
Labels: spec:webauthn-registries

#1369 Add clearer recommendation on what to do with transport hints
  index.bs
Labels: subtype:rp-ops, type:editorial

#1393 Use Python 3.7 for Travis-CI
  .travis.yml
Labels: type:process

#1387 Default to ES256 and RS256 if pubKeyCredParams is empty
  index.bs
Labels: type:technical
