Repository w3c/webauthn, pull requests merged in 2020-01, with the labels that each got.

#1357 Fix typo
  index.bs
Labels: type:editorial

#1359 Add note about risk of ignoring excludeCredentials with mismatched transports
  index.bs
Labels: subtype:impl-cons, type:editorial

#1361 Clarify exts client extension output
  index.bs
Labels: subtype:extensions, type:editorial

#1364 remove 'lightning' AuthenticatorTransport enum value
  index.bs
Labels: type:technical

#1365 update CTAP reference to point to fido-client-to-authenticator-protocol-v2.0-ps-20190130.html
  index.bs
Labels: type:editorial
