Repository w3c/webauthn, pull requests merged in 2020-06, with the labels that each got.

#1420 Specify more about COSE algorithms.
  index.bs
Labels: type:technical

#1426 Update examples to use current Extensions
  index.bs
Labels: subtype:extensions, type:editorial

#1428 Document how to use update-bikeshed-cache.sh
  README.md
Labels: type:process

#1433 fix "present" link errors along with a couple others
  index.bs
Labels: type:editorial

#1330 Enrichen registration and authentication ceremonies definitions
  index.bs
Labels: type:editorial

#1439 Add note about extensions not using ext ID as entry key
  index.bs
Labels: type:editorial

#1402 Add `largeBlob` extension.
  index.bs
Labels: subtype:extensions, type:technical

#1443 Clarify How Client Data is Sent to Authenticator
  index.bs
Labels: type:editorial
