Repository w3c/webauthn, pull requests merged in 2021-05, with the labels that each got.

#1610 Install Bikeshed from PyPI instead of Git clone
  .travis.yml
Labels: type:process

#1609 Fix incorrect authenticator operation reference in §6.1.2
  index.bs
Labels: type:editorial

#1607 Remove mention of ECDAA from Figure 6
  images/fido-attestation-structures.svg
  index.bs
Labels: type:editorial

#1600 Remove user handle "MAY be null" statement
  index.bs
Labels: type:technical

#1599 Move JC to former editors
  index.bs
Labels: type:editorial

#1585 Update CTAP reference.
  index.bs
Labels: type:editorial
