Repository w3c/webauthn, pull requests merged in 2021-07, with the labels that each got.

#1636 Remove trailing whitespace throughout
  index.bs
Labels: type:editorial

#1630 Remove TokenBinding
  index.bs
Labels: type:technical

#1655 Denote crossOrigin in client data as OPTIONAL
  index.bs
Labels: type:editorial

#1654 Fix inconsistency in RP directions for credential transports
  index.bs
Labels: subtype:rp-ops, type:technical
