Repository w3c/webauthn, pull requests merged in 2022-10, with the labels that each got.

#1805 Fix incorrect use of options variable: rename to pkOptions
  index.bs
Labels: type:editorial, stat:puntable

#1796 Fix broken cross-spec references
  index.bs
Labels: type:editorial

#1768 Fix dangling language in WebAuthn Extensions section
  index.bs
Labels: type:editorial

#1807 Move state updates to last in RP verification steps
  index.bs
Labels: type:editorial

#1804 Replace obsolete RFC8152 with RFC9052 and RFC9053
  index.bs
Labels: type:editorial, stat:Blocking

#1663 device public key extension
  index.bs
Labels: type:technical

#1815 Fix broken links to steps in RP ops from DPK extension
  index.bs
Labels: type:editorial
