Repository w3c/webauthn, pull requests merged in 2022-07, with the labels that each got.

#1732 Re-add the PRF extension.
  index.bs
Labels: type:technical, subtype:extensions

#1770 Disambiguate autolink references
  index.bs
Labels: type:editorial

#1762 Sections for client extensions and authenticator extensions
  index.bs
Labels: type:editorial

#1778 first version of issue templates
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/editorial-change--.md
  .github/ISSUE_TEMPLATE/technical-change--.md
  .github/ISSUE_TEMPLATE/use-case-feature--.md
  .github/ISSUE_TEMPLATE/wg-administrivia--.md
Labels: type:process

#1784 Fix heading level for prf extension
  index.bs
Labels: type:editorial

#1776 Add BE/BS flags to diagrams, and fix alignments and line widths
  images/fido-attestation-structures.svg
  images/fido-signature-formats-figure1.svg
Labels: type:editorial

#1755 Add "hybrid" as a transport.
  index.bs
Labels: type:technical
