Repository w3c/webauthn, pull requests merged in 2023-12, with the labels that each got.

#2005 Disambiguate "this value" in authenticatorDisplayName description
  index.bs
Labels: type:editorial

#2003 Fix references to credential private key that should be credential source
  index.bs
Labels: type:editorial

#2001 Fix incorrect reference in Add Virtual Authenticator
  index.bs
Labels: type:technical, type:editorial, subtype:algorithms/WebIDL

#1999 Add backup flags to virtual authenticator
  index.bs
Labels: type:technical

#1991 Don't define a [[preventSilentAccess]] internal method
  index.bs
Labels: type:editorial
