Repository w3c/webauthn, pull requests merged in 2023-11, with the labels that each got.

#1995 Add credProps client processing step to set authenticatorDisplayName
  index.bs
Labels: type:technical, subtype:extensions, process:meta-pr

#1855 Recommend duration of challenge validity
  index.bs
Labels: type:editorial

#1986 Tweaks for bikeshed
  .bikeshed-include/copyright.include
  .bikeshed-include/status-WD.include
  index.bs
Labels: type:editorial

#1957 devicePubKey → supplementalPubKeys
  index.bs
Labels: type:technical

#2000 Clarify validation step for packed attestation certificate for RPs.
  index.bs
Labels: type:editorial
