Repository w3c/webauthn, pull requests merged in 2023-10, with the labels that each got.

#1971 Highlight that filtering all pubKeyCredParams is an error.
  index.bs
Labels: type:editorial

#1981 Remove [SameObject] attribute from PublicKeyCredential.authenticatorAttachment
  index.bs
Labels: type:technical, subtype:algorithms/WebIDL

#1983 Update GitHub Actions workflow
  .github/workflows/build-validate-publish.yml
Labels: process:meta-pr

#1985 [meta-PR] Retain both aaguid definitions
  index.bs
Labels: type:editorial, process:meta-pr

#1950 Add `compound` attestation format
  index.bs
Labels: type:technical, @Risk

#1880 Add authenticatorDisplayName to credProps
  index.bs
Labels: stat:Discuss, subtype:extensions, subtype:FeatureProposal, @Risk
