Repository w3c/webauthn, pull requests merged in 2023-08, with the labels that each got.

#1911 Disambiguate [=Window=] links as {{Window}}
  index.bs
Labels: type:editorial

#1931 Update Authenticator Definition
  index.bs
Labels: type:editorial

#1930 Add security consideration section "Validating the origin of a credential"
  index.bs
Labels: type:editorial

#1914 Address description of uses, and requirements for supplying userHandle
  index.bs
Labels: type:technical

#1884 Add a `hints` element for both `create` and `get`.
  index.bs
Labels: @Risk
