Repository w3c/webauthn, pull requests merged in 2024-08, with the labels that each got.

#2047 Help RP's understand actionable exceptions from `create()` and `get()`
  index.bs
Labels: type:editorial

#2110 Reorder PublicKeyCredentialDescriptorJSON values to match PublicKeyCredentialDescriptor
  index.bs
Labels: type:editorial, subtype:algorithms/WebIDL

#2109 Drop the supplementalPubKeys extension
  index.bs
Labels: type:technical

#2120 Change `*ResponseJSON.id` to `DOMString`
  index.bs
Labels: type:technical

#2114 Move topOrigin definition after crossOrigin
  index.bs
Labels: type:editorial, subtype:algorithms/WebIDL

#2108 Add PR template
  .github/pull_request_template.md
Labels: type:process

#2115 Change type of credProps.authenticatorDisplayName to DOMString
  index.bs
Labels: type:technical, subtype:extensions, subtype:algorithms/WebIDL

#2125 Fix Credential*Options/PublicKeyCredential*Options confusion in RP ops
  index.bs
Labels: type:editorial, subtype:rp-ops

#2093 Add Signal API
  index.bs
Labels: type:technical

#2131 Update CONTRIBUTING.md for non-member IPR commitment
  CONTRIBUTING.md
Labels: type:process
