Repository w3c/webauthn, pull requests merged in 2024-07, with the labels that each got.

#2046 Various improvements to conditionalCreate/Mediation discoverability and uniformity
  index.bs
Labels: type:editorial

#2073 Apply RFC 8264 enforcement only to non-empty strings
  index.bs
Labels: type:technical

#2098 Relax PublicKeyCredentialRequestOptions.rpId to DOMString
  index.bs
Labels: type:technical, subtype:algorithms/WebIDL
