Repository w3c/webauthn, pull requests merged in 2024-11, with the labels that each got.

#2167 Move extension processing to after signature verification, and modernize it
  index.bs
Labels: type:technical, type:editorial, subtype:rp-ops, @Risk

#2193 Clarify use creating and verifying TPM attestation statements.
  index.bs
Labels: type:editorial

#2194 Delete authenticatorDisplayName
  index.bs
Labels: type:technical, subtype:extensions

#2195 Drop outdated "Issue 1" from spec
  index.bs
Labels: type:editorial

#2200 chore: Small tweak to PR template
  .github/pull_request_template.md
Labels: type:process

#2197 Merge branch 'level3' into branch 'main'
  index.bs
Labels: type:process
