Repository w3c/webauthn, pull requests merged in 2024-10, with the labels that each got.

#2148 Add userName and userDisplayName to webdriver
  index.bs
Labels: @Risk

#2173 Acknowledge Zack Newman for reviews and contributions
  index.bs
Labels: type:editorial

#2171 Acknowledge Simone Onofri and Philippe Le Hégaret as W3C Team Contacts
  index.bs
Labels: type:editorial

#2155 Mark Android SafetyNet attestation as deprecated.
  index.bs
Labels: type:technical

#2159 Deprecate rp.name
  index.bs
Labels: type:technical, subtype:rp-ops

#2165 Fix Unicode example syntax
  index.bs
Labels: type:editorial

#2180 Remove apparent reference to non-existent [[Get]] internal method
  index.bs
Labels: type:editorial, subtype:credman

#2179 Extract macros for referring to [[Create]] and [[DiscoverFromExternalSource]]
  index.bs
Labels: type:editorial

#2175 Fix encoding and syntax highlighting of example code
  index.bs
Labels: type:editorial

#2174 Add test vectors for PRF extension
  index.bs
Labels: type:editorial

#2168 Don't return an algorithm from [[DiscoverFromExternalSource]]
  index.bs
Labels: type:editorial, subtype:credman, @Risk

#2182 Fix typo in reference to variable |effectiveDomain|
  index.bs
Labels: type:editorial

#2181 Drop definition "User Credential" unused since PR #2109
  index.bs
Labels: type:editorial

#2176 Non-incrementing signature counters could be due to race condition
  index.bs
Labels: type:editorial

#2163 Add [credential record/authenticatorDisplayName] handling to RP operations
  index.bs
Labels: type:technical, subtype:rp-ops

#2166 Validate CollectedClientData.crossOrigin in RP ops
  index.bs
Labels: type:technical, subtype:rp-ops

#2183 Add warning about sending PRF outputs to server
  index.bs
Labels: type:editorial, subtype:extensions, subtype:rp-ops
