Repository w3c/webauthn, pull requests merged in 2024-12, with the labels that each got.

#2218 Link "Object" to WebDriver instead of File API
  index.bs
Labels: type:editorial

#2216 Fix CDDL inconsistencies in attStmtType and compound format
  index.bs
Labels: type:editorial

#2214 Clarify behaviour of duplicate pubKeyCredParams and attestationFormats
  index.bs
Labels: type:editorial

#2215 Store/update credential record last in RP ops
  index.bs
Labels: type:technical, subtype:rp-ops

#2221 Fix AuthenticationExtensionsAuthenticatorInputs/Outputs CDDL
  index.bs
Labels: type:editorial

#2217 Make remaining `USVString`s `DOMString`s
  index.bs
Labels: type:technical

#2209 Add test vectors
  index.bs
Labels: type:editorial
