Repository w3c/webauthn, pull requests merged in 2024-01, with the labels that each got.

#1923 Add new getClientCapabilities method
  index.bs
Labels: type:technical, privacy-tracker

#2011 Mark SPK's `signatures` output as required.
  index.bs
Labels: type:technical

#1997 Drop assertion-time attestation.
  index.bs
Labels: type:technical

#2015 Fix Bikeshed lint
  index.bs
Labels: type:editorial

#2012 Expand upon the definition of "unsigned extension outputs"
  index.bs
Labels: type:editorial
