Repository w3c/webauthn, pull requests merged in 2024-09, with the labels that each got.

#2141 Add BE/BS steps to authData generation
  index.bs
Labels: subtype:underspecifiedBehaviors

#2127 Codify semantic line breaks as editorial convention
  CONTRIBUTING.md
Labels: type:editorial, type:process

#2138 Adds dfn for passkey in passkey platform authenticator and exports
  index.bs
Labels: type:editorial

#2104 Add topOrigin to the limited verification algorithm.
  index.bs
Labels: type:technical

#2129 Rename PublicKeyCredentialHints to PublicKeyCredentialHint
  index.bs
Labels: type:technical

#2126 Clarify meaning of "unless" in UP flag validation
  index.bs
Labels: type:editorial, subtype:rp-ops

#2145 Clarify behaviour of duplicate hints
  index.bs
Labels: type:technical, subtype:underspecifiedBehaviors, @Risk

#2134 Update obsolete privacy concerns about throwing errors early
  index.bs
Labels: type:technical, subtype:impl-cons, @Risk

#2149 Remove bikeshed workaround
  index.bs
Labels: type:editorial

#1954 Enterprise packed attestation guidance
  index.bs
Labels: type:editorial, @Risk
