Repository w3c/webauthn, pull requests merged in 2025-05, with the labels that each got.

#2284 Add JSON partial dictionaries for extensions
  index.bs
Labels: type:technical, type:editorial

#2289 Add scripts used to generate test vectors
  .github/workflows/check-test-vectors.yml
  index.bs
  test-vectors/README.md
  test-vectors/inject-generated-content.sh
  test-vectors/poetry.lock
  test-vectors/pyproject.toml
  test-vectors/webauthn-prf-test-vectors.py
  test-vectors/webauthn-test-vectors.py
Labels: type:editorial, type:process

#2290 Add and prefer fully-specified COSE algorithm identifers in test vectors
  index.bs
  test-vectors/poetry.lock
  test-vectors/pyproject.toml
  test-vectors/webauthn-test-vectors.py
Labels: type:editorial, process:meta-pr

#2292 Add `attestationFormats` to the list of new features since L2
  index.bs
Labels: type:editorial

#2283 Account for new fully-specified ECDSA and Ed448 COSEAlgorithmIdentifiers
  index.bs
  test-vectors/poetry.lock
  test-vectors/pyproject.toml
  test-vectors/webauthn-test-vectors.py
Labels: type:technical
