Repository w3c/webauthn, pull requests merged in 2025-01, with the labels that each got.

#2196 Make NOTEs non-normative
  index.bs
Labels: type:editorial

#2230 Proposed changes from review of PR 2224
  index.bs
Labels: type:editorial, process:meta-pr

#2232 Add more to L3 revision history
  index.bs
Labels: type:editorial, process:meta-pr

#2227 Fix bikeshed warnings
  images/fido-attestation-structures.svg
  images/fido-signature-formats-figure1.svg
  images/fido-signature-formats-figure2.svg
  images/string-truncation.svg
  images/webauthn-authentication-flow-01.svg
  images/webauthn-registration-flow-01.svg
  index.bs
Labels: type:editorial

#2111 Cleanup: Manual References
  index.bs
Labels: type:editorial, @Risk

#2224 Adding Revision history section
  index.bs
Labels: type:editorial

#2239 Say that tokenBinding is RESERVED in History
  index.bs
Labels: type:editorial, priority:high

#2242 chore: Update issue template
  .github/ISSUE_TEMPLATE/config.yml
Labels: type:process

#2139 Update Use Cases for L3
  index.bs
Labels: type:editorial, @Risk
